name: CI
on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up toolchain
      run: rustup show

    - name: Run clippy
      run: cargo clippy --all-features

  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up toolchain
      run: rustup show

    - name: Run tests
      run: cargo test --no-default-features

  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt install --yes make mtools parted
        rustup show

    - name: Build UEFI application
      run: make
