name: CI
on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up toolchain
      run: rustup show

    - name: Run clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up toolchain
      run: rustup show

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-default-features

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt install --yes make mtools parted
        rustup show

    - name: Build UEFI application
      run: make
